apiVersion: v1
kind: Pod
metadata:
  name: nlp-container
spec:
  restartPolicy: Never
  containers:
  - name: nlp-container
    image: "python:3.10"
    command: ["sh", "-c", "sleep 60m"]
    args: []
    resources:
      limits:
        cpu: 20
        memory: "32Gi"
      requests:
        cpu: 20
        memory: "32Gi"
    volumeMounts:
    - name: datasetvolume
      mountPath: "/dataset"
  volumes:
  - name: datasetvolume
    persistentVolumeClaim:
      claimName: nlp-data
