python3 decode_librispeech.py \
    --batch_size 1 \
    --beam_size 5 \
    --use_gpt \
    --gpt_kind gpt2 \
    --shallow_fusion \
    --use_icl \
    --index_path ./librispeech-pc/filtered_merged.faiss \
    --csv_path ./librispeech-pc/filtered_merged.csv \
    --split $YOUR_DATASET_SPLIT \
    --output_path $YOUR_OUTPUT_PATH \
    --cache_root $YOUR_CACHE_ROOT \
    --sample_random \