python3 decode_librispeech.py \
    --batch_size 1 \
    --use_gpt \
    --gpt_kind gpt2 \
    --shallow_fusion \
    --use_icl \
    --index_path ./merged_filtered.faiss \
    --csv_path ./merged_filtered.csv \
    --beam_size 5 \
    --split test-other \
    --output_path output/prefix_other.txt \
    --cache_root nlp/.data