python3 decode_librispeech.py \
    --batch_size 1 \
    --beam_size 5 \
    --use_gpt \
    --gpt_kind gpt2 \
    --shallow_fusion \
    --use_icl \
    --index_path ./librispeech-pc/filtered_merged.faiss \
    --csv_path ./librispeech-pc/filtered_merged.csv \
    --split test-clean \
    --output_path ./output/test-clean-pc-random.txt \
    --cache_root nlp/.data \
    --sample_random