apiVersion: v1
kind: Pod
metadata:
  name: download-pod
spec:
  restartPolicy: Never
  containers:
  - name: download-container
    image: "python:3.10"
    command: ["sh", "-c"]
    args: ["cd /dataset && apt-get update && apt-get upgrade -y && apt-get install wget -y && cd /dataset && wget https://www.openslr.org/resources/12/dev-clean.tar.gz && wget https://www.openslr.org/resources/12/test-clean.tar.gz"]
    resources:
      limits:
        cpu: 4
        memory: "32Gi"
      requests:
        cpu: 4
        memory: "32Gi"
    volumeMounts:
    - name: datasetvolume
      mountPath: "/dataset"
  volumes:
  - name: datasetvolume
    persistentVolumeClaim:
      claimName: nlp-data